[project]
name = "repl-nix-tiktokadsloginautomator"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "imapclient>=3.0.1",
    "pyngrok>=7.2.1",
    "requests>=2.32.3",
    "selenium>=4.26.1",
]
